### ISSUE TITLE
discord link has expired

### ISSUE THREAD

**Issue by cribbageSTARSHIP** [beclab/Terminus#375]
Hello, 

Your discord link has expired; is the discord still active? This project is interesting. I have a spare machine and would love to take it for a test drive, however I have questions.

Thank you

**Comment by cal-weng** [comment]
Hi @cribbageSTARSHIP Thanks for your interest in our project. And sorry that you couldn't join the Discord via the provided link.  Could you please let us know which link did you use? We tried the two links provided on the official website (jointerminus.com) and GitHub. Both of the two worked for us.

Anyway, for now, you can use this link to join our channel: https://discord.gg/jwz8Bz7rwg
Look forward to meeting you there and answering your questions.

**Comment by cribbageSTARSHIP** [comment]
https://discord.com/invite/ShjkCBs2 <- thats the hyperlink found on this page: https://github.com/beclab/Terminus

**Comment by hozansahin** [comment]
Hey! @cal-weng 
discord link has expired Again! 
Please update

**Comment by fnalways** [comment]
Hi @hozansahin 
The Discord link seems to be working fine on our end, but to better understand the issue you're experiencing, could you let us know which link you're using and where you found it (e.g., GitHub README)? This will help us troubleshoot more effectively. 
Also here's a fresh invite link you can use to join the channel: https://discord.gg/gFxh8sJubX. Please let us know if this one works for you. Thanks.

**Comment by hozansahin** [comment]
Hi @fnalways 
I was using the link found in the readme.md. So this one ( https://discord.com/invite/BzfqrgQPDK )
It didn't work for me. Now I have participated with the link you sent, thank you very much 👏
