### ISSUE TITLE
Duplicated docs

### ISSUE THREAD

**Issue by ulissesjdeo** [beclab/Terminus#552]
Hey, I found that pages [1](https://docs.jointerminus.com/overview/introduction/getting-started/linux.html) and [2](https://docs.jointerminus.com/how-to/terminus/setup/install/linux.html) basically have the same content, is it designed to be that way? I didn't see nothing wrong in any of them but I think it would make harder to keep it up to date

**Comment by ulissesjdeo** [comment]
I saw the button "[Install Terminus on Linux](https://docs.jointerminus.com/how-to/terminus/setup/install/linux.html)", it is for more detailed instructions. I'm sorry

**Comment by cal-weng** [comment]
@ulissesjdeo Thanks for your feedback. We understand it might be a bit confusing and we are working on a major refactoring to the doc available soon.
